### ISSUE TITLE
CPP Example for convertToVerticesAndFaces throws C2036 Error

### ISSUE THREAD

**Issue by pmcarow** [Innoptech/OpenSTL#19]
The readme snippet throws C2036 Error `std::array<size_t,3> *: unknown size`

``` 
using namespace openstl

std::vector triangles = {
    //        normal,             vertices 0,         vertices 1,        vertices 2
    Triangle{{0.0f, 0.0f, 1.0f}, {1.0f, 1.0f, 1.0f}, {2.0f, 2.0f, 2.0f}, {3.0f, 3.0f, 3.0f}},
    Triangle{{0.0f, 0.0f, 1.0f}, {2.0f, 2.0f, 2.0f}, {3.0f, 3.0f, 3.0f}, {4.0f, 4.0f, 4.0f}}
};

const auto& [vertices, faces] = convertToVerticesAndFaces(triangles);

**Comment by jeanchristopheruel** [comment]
Thanks for your report! I suspect you are running this on a windows os. I assumed array is always implicitly defined in <vector> but it seems not to be the case for some std implementation like in MSVC. 

Should now be fixed in 1.2.10, but I do not have any windows machine to try it on. Any feedback would be well appreciated.

**Comment by pmcarow** [comment]
This works now! Note that I was using C++ 14 (Visual Studio default for some reason), and had to change to C++ 17 to get the auto type to work. Thank you!

**Comment by jeanchristopheruel** [comment]
Thanks for the feedback! I'm closing this issue but I am also opening a new one regarding the C++17 requirement issue.
